overhaul getbtpcli

diff --git a/scripts/getbtpcli b/scripts/getbtpcli
--- a/scripts/getbtpcli
+++ b/scripts/getbtpcli
@@ -1,47 +1,100 @@
 #!/usr/bin/env bash
 
-# getbtpcli - Get (latest) btp CLI
+# getbtpcli - Get (latest) btp CLI. Has a test mode (-t or --test) to
+# just retrieve & check what the latest version is, without installing.
 
 set -o errexit
+
+declare -r ARCH=darwin-amd64
 declare -r TARGETDIR="$HOME/bin"
-declare -r licence="tools.hana.ondemand.com/developer-license-3_1.txt"
-declare tempdir ver
+declare -r LICENCE="tools.hana.ondemand.com/developer-license-3_1.txt"
 
-# Move to a temporary directory for extracting and checking
-tempdir="$(mktemp -d)"
-cd "$tempdir"
+confirm_licence_acceptance() {
 
-echo "Proceed (with Enter) only if you accept the SAP Developer Licence 3.1"
-echo -n "(see https://$licence) ..."
-read -r proceed
+  # Ensure licence acceptance
 
-# Download tarball of latest version and unpack it
-echo Downloading and extracting ...
-curl \
-  --fail \
-  --silent \
-  --location \
-  --header "Cookie: eula_3_1_agreed=$licence; path=/;" \
-  "https://tools.hana.ondemand.com/additional/btp-cli-darwin-amd64-latest.tar.gz" \
-  | tar \
-    --extract \
-    --strip-components 1 \
-    --verbose \
-    --gunzip \
-    --file - \
-    "darwin-amd64/btp"
+  local proceed
+  echo "Proceed (with Enter) only if you accept the SAP Developer Licence 3.1"
+  echo -n "(see https://$LICENCE) ..."
+  # shellcheck disable=2034
+  read -r proceed
 
-# Remove any Apple quarantine
-xattr -d com.apple.quarantine ./btp 2> /dev/null || true
+}
 
-# Determine the version
-ver="$(./btp --version 2> /dev/null | ggrep -P -o '(?<=v)\d+\.\d+\.\d+')"
+dequarantine() {
 
-# Move to target directory and set symlink then remove temporary dir
-cd "$TARGETDIR" \
-  && mv "$tempdir/btp" "./btp-$ver" \
-  && ln -f -s "btp-$ver" btp \
-  && rmdir "$tempdir"
+  # Remove any Apple quarantine
 
-# Show version
-"./btp-$ver" --version 2> /dev/null
+  local file=$1
+  xattr -d com.apple.quarantine "$file" 2> /dev/null || true
+
+}
+
+retrieve() {
+
+  # Download tarball of latest version and extract the btp binary
+
+  local tempdir=$1
+
+  curl \
+    --fail \
+    --silent \
+    --location \
+    --header "Cookie: eula_3_1_agreed=$LICENCE; path=/;" \
+    "https://tools.hana.ondemand.com/additional/btp-cli-$ARCH-latest.tar.gz" \
+    | tar \
+      --file - \
+      --extract \
+      --gunzip \
+      --directory "$tempdir" \
+      --strip-components 1 \
+      "$ARCH/btp"
+
+}
+
+get_version() {
+
+  # Determine the version (uses the proper grep, from GNU)
+
+  local file=$1
+  "$file" --version 2> /dev/null | ggrep -P -o '(?<=v)\d+\.\d+\.\d+'
+
+}
+
+main() {
+
+  # Move to a temporary directory; extract and check version, and
+  # (unless --test mode) install, setting up symlink.
+
+  local tempdir ver testmode=false
+
+  # Determine if we're in test mode
+  [[ $1 =~ ^(-t|--test)$ ]] && testmode=true
+
+  # Allow the user to cancel if they don't accept the licence
+  [[ $testmode = false ]] && confirm_licence_acceptance
+
+  # Set up temporary directory and move into it
+  tempdir="$(mktemp -d)"
+
+  # Retrieve latest tarball and extract the binary
+  retrieve "$tempdir"
+
+  # Determine version
+  ver="$(get_version "$tempdir/btp")"
+  echo "Latest version is $ver"
+
+  # Unless we're in test mode, move binary to target directory and
+  # set symlink
+  if [[ $testmode = false ]]; then
+    cd "$TARGETDIR" \
+      && mv "$tempdir/btp" "./btp-$ver" \
+      && ln -f -s "btp-$ver" btp
+  fi
+
+  # Clean up by removing temporary directory
+  rm -rf "$tempdir"
+
+}
+
+main "$@"
